image:
  file: dockerfile  
tasks:
  - init: yarn install
    command: cp -r /workspace/MydatascienceEnv/.jupyter /home/gitpod/
ports:
  - port: 8000
    onOpen: open-preview    
  - port: 8888
    onOpen: open-preview
