image:
  file: dockerfile  
tasks:
  - init: echo "Hello !!! welcome to the DataSciece Dev-container by Yogesh Bang !!!"
    command: cp -r /workspace/MydatascienceEnv/.jupyter /home/gitpod/
ports:
  - port: 8000
    onOpen: open-preview    
  - port: 8888
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
    
