image:
  file: dockerfile  
tasks:
  - init: gp preview https://bangyogesh.github.io/datascience-dev-container.html
    command: cp -r /workspace/MydatascienceEnv/.jupyter /home/gitpod/
ports:
  - port: 8000
    onOpen: open-preview    
  - port: 8888
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
    
